spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9291
        streams:
          binder:
            brokers: kafka:9291

server:
  port: 8000

logging:
  level:
    root: info
    org.apache.zookeeper: error
    org.apache.kafka: error
    io.spring.scs_kotlin_kstream_sample: debug